name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag-build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Bump Tag
        id: bump
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build shaded jar
        run: ./gradlew --no-daemon shadowJar

      - name: Upload artifact (workflow)
        uses: actions/upload-artifact@v4
        with:
          name: plugin-artifacts
          path: |
            **/build/libs/*.jar
          if-no-files-found: error

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          generate_release_notes: true
          files: |
            **/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
